name: Install Node
on:
 workflow_call:
   secrets:
     ENV:
       required: true

jobs:
  install_node:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    # Setting Up NodeJS
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x' 
    # Call Env from Secrets
    - run: | 
        echo "${{ secrets.ENV }} " >> .env
        cat .env
    # Installing Dependencies
    - name: Install dependencies
      run: npm install -f 
     # Upload to Artifacts    
    - uses: actions/upload-artifact@v4
      with:
        name: NODE_FILES
        path: ./
